In [1]:
import requests
import pandas as pd

In [2]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

In [3]:
response = requests.get(url)

In [4]:
raw_data = response.json()

In [5]:
response.status_code

200

In [6]:
data = pd.json_normalize(raw_data)

In [7]:
data.head()

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,...,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Engine failure at 33 seconds and loss of vehicle,[],[],...,None,None,[],[],None,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-fa...,https://en.wikipedia.org/wiki/DemoSat,NaN
1,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Successful first stage burn and transition to ...,[],[],...,None,None,[],[],None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-roc...,https://en.wikipedia.org/wiki/DemoSat,NaN
2,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,False,Residual stage 1 thrust led to collision betwe...,[],[],...,None,None,[],[],None,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1...,https://en.wikipedia.org/wiki/Trailblazer_(sat...,NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,False,0.0,5e9d0d95eda69955f709d1eb,True,Ratsat was carried to orbit on the first succe...,[],[],...,None,None,[],[],None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,None,NaN,False,False,0.0,5e9d0d95eda69955f709d1eb,True,None,[],[],...,None,None,[],[],http://www.spacex.com/press/2012/12/19/spacexs...,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1...,https://en.wikipedia.org/wiki/RazakSAT,NaN

In [10]:
falcon9_data = data[data['rocket'] != '5e9d0d95eda69955f709d1eb'].copy()

In [11]:
len(falcon9_data)

102

In [12]:
falcon9_data.head()

,static_fire_date_utc,static_fire_date_unix,tbd,net,window,rocket,success,details,crew,ships,...,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
5,2010-03-13T00:00:00.000Z,1.268438e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,None,[],[],...,None,None,[],[],http://forum.nasaspaceflight.com/index.php?act...,https://www.youtube.com/watch?v=nxSxgBKlYws,nxSxgBKlYws,http://www.spacex.com/news/2013/02/12/falcon-9...,https://en.wikipedia.org/wiki/Dragon_Spacecraf...,NaN
6,2010-12-04T00:00:00.000Z,1.291421e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,None,[],[5ea6ed2d080df4000697c901],...,None,None,[],[],http://www.spacex.com/files/downloads/cots1-20...,https://www.youtube.com/watch?v=cdLITgWKe_0,cdLITgWKe_0,https://en.wikipedia.org/wiki/SpaceX_COTS_Demo...,https://en.wikipedia.org/wiki/SpaceX_COTS_Demo...,NaN
7,2012-04-30T00:00:00.000Z,1.335744e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,"Launch was scrubbed on first attempt, second l...",[],[5ea6ed2d080df4000697c901],...,None,None,[],[],https://www.nasa.gov/pdf/649910main_cots2_pres...,https://www.youtube.com/watch?v=tpQzDbAY7yI,tpQzDbAY7yI,https://en.wikipedia.org/wiki/Dragon_C2%2B,https://en.wikipedia.org/wiki/Dragon_C2%2B,NaN
8,2012-09-29T00:00:00.000Z,1.348877e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,"CRS-1 successful, but the secondary payload wa...",[],[5ea6ed2d080df4000697c902],...,None,None,[],[],https://www.nasa.gov/pdf/694166main_SpaceXCRS-...,https://www.youtube.com/watch?v=-Vk3hiV_zXU,-Vk3hiV_zXU,https://www.nasa.gov/mission_pages/station/mai...,https://en.wikipedia.org/wiki/SpaceX_CRS-1,NaN
9,2013-02-25T18:30:00.000Z,1.361817e+09,False,False,0.0,5e9d0d95eda69973a809d1ec,True,Last launch of the original Falcon 9 v1.0 laun...,[],[5ea6ed2d080df4000697c902],...,None,None,[],[],https://www.nasa.gov/sites/default/files/files...,https://www.youtube.com/watch?v=ik0ElKl5kW4,ik0ElKl5kW4,https://en.wikipedia.org/wiki/SpaceX_CRS-2,https://en.wikipedia.org/wiki/SpaceX_CRS-2,NaN

In [13]:
fallback_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv"
final_data = pd.read_csv(fallback_url)

In [14]:
final_data.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

In [15]:
mean_mass = final_data["PayloadMass"].mean()

In [16]:
final_data["PayloadMass"].fillna(mean_mass, inplace=True)

In [17]:
final_data["PayloadMass"].isnull().sum()

0